version: '2'

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - misspell
    - nakedret
    - nilerr
    - nilnesserr
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - unconvert

formatters:
  enable:
    - goimports
